/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:978b65c1-b26b-46e8-8625-cec556cf80fd",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_Ud3ioHAoU",
    "aws_user_pools_web_client_id": "3u6iv9d8bdg8fpqq27aaacnqbu",
    "oauth": {}
};


export default awsmobile;
